# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbhrp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: MySQL
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:      
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        
# SQL SERVER
#spring:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databasename=dbhrp
#    username: sa
#    password: SqlServer
#  jpa:
#    database: sql-server
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    

server:
  port: 8081
  
  
  
  